language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8
  - sudo apt-get install g++-4.8
  - sudo apt-get install binutils-gold
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

before_script:
  - mkdir src inst obj
  - git clone https://github.com/vgvassilev/llvm.git src
  - (cd src && git checkout cling-patches)
  - git clone https://github.com/vgvassilev/clang.git src/tools/clang
  - (cd src/tools/clang && git checkout cling-patches)
  - git clone https://github.com/vgvassilev/cling.git src/tools/cling
  - cd src
  - cd ../obj
  - travis_retry ../src/configure --prefix=`pwd`/../inst --disable-docs --disable-bindings --disable-visibility-inlines-hidden --disable-clang-rewriter --disable-clang-static-analyzer --disable-clang-arcmt --disable-compiler-version-checks --enable-targets=host

script:
  - travis_retry make -j4 -k
  - travis_retry make -j4 -k
  - travis_retry make install
  - cd tools/cling
  - make test LIT_ARGS=--no-progress-bar

branches:
  only:
    - master

notifications:
  recipients:
    - vvasilev@cern.ch
    #- cling-dev@cern.ch

  email:
    on_success: change
    on_failure: always
  #irc:
  #channels:
    #- "chat.freenode.net#rubinius"
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

os:
  - linux
#  - osx
